version: 2.1

orbs:
   slack: circleci/slack@3.4.2

jobs:

  test:
    working_directory: ~/ci
    docker:
      - image: district0x/cljs-dev
    steps:
      - checkout
      - restore_cache:
          name: Restore m2 package cache
          keys:
            - maven-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - maven-dependencies-
      - run: lein deps
      - save_cache:
          name: Save m2 package cache
          paths:
            - ~/.m2
          key: maven-dependencies-{{ checksum "project.clj" }}
      - run: lein doo node "test" once
      - run: lein doo node "async-test" once
      - slack/status:
          channel: travis-ci
          mentions: $CIRCLE_USERNAME

  deploy:
   machine: true
   steps:
     - checkout
     - run:
         name: Deploy to clojars
         command: lein release :patch
     - slack/status:
         channel: travis-ci
         mentions: $CIRCLE_USERNAME
         fail_only: true

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          context: district0x
      - approve_deploy:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master
      - slack/approval-notification:
          context: district0x
          message: Pending approval
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          context: district0x
          requires:
            - approve_deploy
